# Introduction to NumPy

## Array Creation

In [1]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
arr = np.zeros(4)
print(arr)
arr = np.arange(1, 4, 2)
print(arr)
arr = np.random.rand(2)
print(arr)
arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.71403528 0.2557306 ]
[4.9e-324 9.9e-324 1.5e-323]


In [ ]:
arr = np.array(
    [[1, 2, 3], [1, 2, 3]],
    dtype=float
)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full((1, 4), 2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]]


## Array Attributes

In [ ]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=float)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)
print(arr.data)
arr

2
6
float64
(2, 3)
8


array([[1., 2., 3.],
       [1., 2., 3.]])

## Indexing

In [ ]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(arr[0])

arr[1] = 3.0
print(arr)

print(arr[-4])

arr[-3] = 2.0
print(arr)

1.0
[1. 3. 3. 4.]
1.0
[1. 2. 3. 4.]


In [ ]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]])

print(arr[0][3])
print(arr[-2][3])

arr[1] = 3.0
print(arr)

arr[0][-3] = 3.0
print(arr)

4.0
4.0
[[1. 2. 3. 4.]
 [3. 3. 3. 3.]]
[[1. 3. 3. 4.]
 [3. 3. 3. 3.]]


## Slicing

In [ ]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(arr[0])
print(arr[0][0::2])

print(arr[0:2, 1:3])
print(arr[0:2, -4::2])

[1. 2. 3. 4.]
[1. 3.]
[[2. 3.]
 [6. 7.]]
[[1. 3.]
 [5. 7.]]


## Reshaping

In [ ]:
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
print(arr.shape)

arr = np.reshape(arr, (3, 2))
print(arr)
print(arr.shape)

(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


Reshape sai kích thước sẽ báo lỗi:

In [ ]:
arr = np.reshape(arr, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

## Array Operations

In [ ]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 6.0, 7.0, 8.0])

print(arr1 + arr2)
print(np.add(arr1, arr2))

print(arr1 % arr2)
print(np.mod(arr1, arr2))

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [ ]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 2.0, 7.0, 8.0])

print(arr1 < arr2)
print(np.less(arr1, arr2))

print(arr1 != arr2)
print(np.not_equal(arr1, arr2))

## Math Functions

In [ ]:
arr = np.random.rand(2, 3)
print(arr)

print(np.sin(arr))

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[[0.57164665 0.45276667 0.39443753]
 [0.91279844 0.38954444 0.39323189]]
[[0.54101763 0.43745511 0.38428897]
 [0.79121818 0.37976702 0.38317563]]
[[1. 0. 0.]
 [1. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(np.max(arr))

arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])
print(np.max(arr))
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))

4.0
8.0
[5. 6. 7. 8.]
[4. 8.]


## String Functions

In [ ]:
arr1 = np.array(['Iphone: ', 'Price: '])
arr2 = np.array(['15', '$900'])

print(np.char.add(arr1, arr2))
print(np.char.multiply(arr1, 3))
print(np.char.upper(arr1))
print(np.char.equal(arr1, arr2))

['Iphone: 15' 'Price: $900']
['Iphone: Iphone: Iphone: ' 'Price: Price: Price: ']
['IPHONE: ' 'PRICE: ']
[False False]


## Broadcasting

In [ ]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([[1.0], [5.0]])

print(arr1)
print(arr2)

print(np.add(arr1, 3.0))

print(np.add(arr1, arr2))

[1. 2. 3. 4.]
[[1.]
 [5.]]
[4. 5. 6. 7.]
[[2. 3. 4. 5.]
 [6. 7. 8. 9.]]


## Practice - Stack two arrays vertically

In [2]:
arr_1 = np.arange(10).reshape((2, -1))
print("The first array:\n", arr_1)

arr_2 = np.repeat(8, 10).reshape((2, -1))
print("The second array:\n", arr_2)

The first array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
The second array:
 [[8 8 8 8 8]
 [8 8 8 8 8]]


In [4]:
# theo truc doc
print(np.concatenate((arr_1, arr_2), axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]


## Practice - Stack two arrays horizontally

In [5]:
print(np.concatenate((arr_1, arr_2), axis=1))

[[0 1 2 3 4 8 8 8 8 8]
 [5 6 7 8 9 8 8 8 8 8]]


## Practice - Filter elements

In [ ]:
arr = np.array([1, 8, 2, 5, 4, 6, 0, 7, 9, 3])

idx = np.where(arr < 7)
out = arr[idx]
print(out)

out = arr[arr < 7]
print(out)

[1 2 5 4 6 0 3]
[1 2 5 4 6 0 3]


## Practice - Apply a user-defined function

In [ ]:
arr_1 = np.arange(10).reshape((2, -1))
print("The first array:\n", arr_1)

arr_2 = np.array([2, 5, 1, 9, 7, 3, 8, 6, 0, 4]).reshape((2, -1))
print("The second array:\n", arr_2)

def get_max(x, y):
    if x >= y:
        return x
    else:
        return y

element_wise_compare = np.vectorize(get_max, otypes=[int])

out1 = element_wise_compare(arr_1, arr_2)
print("Output using the first method:\n", out1)

out2 = np.maximum(arr_1, arr_2)
print("Output using the second method:\n", out2)

out3 = np.where(arr_1 > arr_2, arr_1, arr_2)
print("Output using the third method:\n", out3)

The first array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
The second array:
 [[2 5 1 9 7]
 [3 8 6 0 4]]
Output using the first method:
 [[2 5 2 9 7]
 [5 8 7 8 9]]
Output using the second method:
 [[2 5 2 9 7]
 [5 8 7 8 9]]
Output using the third method:
 [[2 5 2 9 7]
 [5 8 7 8 9]]


## Length of a Vector

In [ ]:
u = np.array([1, 2, 4, 2])
print("Length of vector u:", np.linalg.norm(u))

Length of vector u: 5.0


## Vector - from list

In [ ]:
list1 = [1, 2, 3]
vector1 = np.array(list1)
print(vector1)

vector2 = np.arange(1, 4, 2)
print(vector2)

[1 2 3]
[1 3]


## Vector Operations

In [ ]:
u = np.array([1, 2, 3, 4])
print(u)
v = np.array([5, 6, 7, 8])
print(v)

print(u + v)
print(np.add(u, v))

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[ 6  8 10 12]


In [ ]:
u = np.array([1, 2, 3, 4])
print(u)
v = np.array([5, 6, 7, 8])
print(v)

print(v - u)
print(np.subtract(v, u))

[1 2 3 4]
[5 6 7 8]
[4 4 4 4]
[4 4 4 4]


In [ ]:
u = np.array([1, 2, 3, 4])
print(u)
v = np.array([5, 6, 7, 8])
print(v)

print(v / u)
print(np.divide(v, u))
print(v // u)
print(v % u)

[1 2 3 4]
[5 6 7 8]
[5.         3.         2.33333333 2.        ]
[5.         3.         2.33333333 2.        ]
[5 3 2 2]
[0 0 1 0]


In [ ]:
u = np.array([1, 2, 3])
alpha = 2

result = alpha * u
print(result)

[2 4 6]


In [ ]:
u = np.array([1, 2, 3, 4])
print(u)
v = np.array([5, 6, 7, 8])
print(v)

print(v * u)
print(u * v)
print(np.multiply(u, v))

[1 2 3 4]
[5 6 7 8]
[ 5 12 21 32]
[ 5 12 21 32]
[ 5 12 21 32]


## Vector Dot Product

In [ ]:
arr = np.array([1., 2., 3.])
print(np.dot(arr, 2))

[2. 4. 6.]


In [ ]:
arr_1 = np.array([1., 2., 3.])
arr_2 = np.array([1., 2., 1.])
print(np.dot(arr_1, arr_2))

8.0


In [ ]:
arr_1 = np.array([
    [3., 4., 1.], [4., 3., 2.]
])
arr_2 = np.array([
    [1., 2.], [0., 1.], [2., 0.]
])
print(np.dot(arr_1, arr_2))

[[ 5. 10.]
 [ 8. 11.]]


## Matrix

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
print(matrix1)

matrix2 = np.random.rand(2, 3)
print(matrix2)

[[1 2]
 [3 4]]
[[0.36584336 0.4117086  0.37127227]
 [0.38190773 0.83729243 0.14880752]]


## Matrix Operations

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[3, 4], [4, 5]])
print(B)

print(A + B)
print(np.add(A, B))

[[1 2]
 [3 4]]
[[3 4]
 [4 5]]
[[4 6]
 [7 9]]
[[4 6]
 [7 9]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[3, 4], [4, 5]])
print(B)

print(A - B)
print(np.subtract(A, B))

[[1 2]
 [3 4]]
[[3 4]
 [4 5]]
[[-2 -2]
 [-1 -1]]
[[-2 -2]
 [-1 -1]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[3, 4], [4, 5]])
print(B)

print(A / B)
print(np.divide(A, B))

[[1 2]
 [3 4]]
[[3 4]
 [4 5]]
[[0.33333333 0.5       ]
 [0.75       0.8       ]]
[[0.33333333 0.5       ]
 [0.75       0.8       ]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[3, 4], [4, 5]])
print(B)

print(A * B)
print(np.multiply(A, B))

[[1 2]
 [3 4]]
[[3 4]
 [4 5]]
[[ 3  8]
 [12 20]]
[[ 3  8]
 [12 20]]
